# Generated by Django 4.2.26 on 2025-11-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(default=1, help_text='Select a language for this book', on_delete=django.db.models.deletion.CASCADE, to='catalog.language'),
        ),
    ]
